config/routes.rb
Rails.application.routes.draw do

  resources :podcasts

end

app/models/podcast.rb
# == Schema Information
#
# Table name: podcasts
#
#  id                     :integer          not null, primary key
#  title                  :string
#  user_id                :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  cast_file_file_name    :string
#  cast_file_content_type :string
#  cast_file_file_size    :integer
#  cast_file_updated_at   :datetime
#

class Podcast < ActiveRecord::Base
	belongs_to :user
	acts_as_mappable
	has_attached_file :cast_file
	validates_attachment_content_type :cast_file, content_type: /\Aaudio/

	validates :title, :cast_file, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  identifier :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
	has_many :podcasts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_current_user
		if !cookies[:user_identifier].nil?
			@user = User.find_by_identifier( cookies[:user_identifier])
			if @user.nil?
				create_user
			else
				@user
			end
		else
			create_user
		end
	end

	def create_user
		@user = User.new
		@user.identifier = generate_token
		@user.save
		cookies[:user_identifier] = @user.identifier
		@user
	end

	def generate_token
    	loop do
      		random_token = SecureRandom.urlsafe_base64(nil, false)
      		break random_token unless User.exists?(identifier: random_token)
    	end
  	end

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)
    @podcast.user_id = get_current_user.id
    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:title, :cast_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Anoncast
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .container
      = yield

app/views/podcasts/_form.html.haml
= simple_form_for @podcast, html: { class: 'form-horizontal' } do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :cast_file, as: :file

  .form-actions
    = f.button :submit

app/views/podcasts/edit.html.haml
.row
	.col-md-12
		%h1
			.text-center Editing podcast

		= render 'form'
		.btn-group
			= link_to 'Show', @podcast, class: 'btn btn-default'
			= link_to 'Back', podcasts_path, class: 'btn btn-default'

app/views/podcasts/index.html.haml
.row
  .col-md-12
    %h1 Podcasts
    = link_to 'New Podcast', new_podcast_path, class: 'btn btn-primary'

    %table.table
      %thead
        %tr
          %th Title
          %th

      %tbody
        - @podcasts.each do |podcast|
          %tr
            %td= podcast.title
            %td
              .btn-group
                = link_to 'Show', podcast, class: 'btn btn-default'
                = link_to 'Edit', edit_podcast_path(podcast), class: 'btn btn-default'
                = link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'

    %br

app/views/podcasts/new.html.haml
.row
	.col-md-12
		%h1
			.text-center New podcast

		= render 'form'

		= link_to 'Back', podcasts_path, class: 'btn btn-default'

app/views/podcasts/show.html.haml
%p
  %b Title:
  = @podcast.title
  %audio{src: @podcast.cast_file.url, preload: 'auto'}

= link_to 'Edit', edit_podcast_path(@podcast)
\|
= link_to 'Back', podcasts_path